# Orb 'circleci/node@3.0.0' resolved to 'circleci/node@3.0.0'
version: 2
jobs:
  build_and_test:
    docker:
    - image: cimg/node:13.11.0
    steps:
    - add_ssh_keys:
        fingerprints: 
        - "9f:b9:63:d2:4d:1c:9b:eb:4f:c5:1c:18:99:96:1d:05"
    - checkout
    - run:
        command: |
          chmod 755 .circleci/deploy.sh
          if [ ! -f "package.json" ]; then
            echo
            echo "---"
            echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
            echo "---"
            echo
            echo "Current directory: $(pwd)"
            echo
            echo
            echo "List directory: "
            echo
            ls
            exit 1
          fi
        name: Checking for package.json.
        working_directory: ~/project
    - restore_cache:
        keys:
        - node-deps-v1-{{ .Branch }}-{{ checksum "~/project/package-lock.json" }}
    - run:
        command: "if [[ ! -z \"\" ]]; then\n  echo \"Running override package installation command:\"\n  \nelse\n  npm ci\nfi\n"
        name: Installing NPM packages
        working_directory: ~/project
    - save_cache:
        key: node-deps-v1-{{ .Branch }}-{{ checksum "~/project/package-lock.json" }}
        paths:
        - ~/.npm
    - run:
        command: npm run test
        name: Run NPM Tests
        working_directory: ~/project
    - run:
        name: DEV
        command: export NODE_ENV=development 
    - run:
        name: Installing NPM packages
        command: "if [[ ! -z \"\" ]]; then\n  echo \"Running override package installation command:\"\n  \nelse\n  npm ci\nfi\n"
        working_directory: ~/project
    # - run:
    #     name: Deploy
    #     command: ./.circleci/deploy.sh
  
  deploy-job:
    - run:
      name: DEV
      command: export NODE_ENV=development

workflows:
  version: 2
  node-tests:
    jobs:
      - build_and_test:
          context: development

      - deploy-job:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
  

# Original config.yml file:
# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test