# Orb 'circleci/node@3.0.0' resolved to 'circleci/node@3.0.0'
version: 2
jobs:
  test_and_deploy:
    docker:
    - image: cimg/node:13.11.0
    steps:
      - add_ssh_keys:
        fingerprints: 
        - "0c:27:47:aa:4c:0f:61:87:c8:7f:bd:91:19:41:06:33"
    - checkout
    - run:
        command: |
        chmod 755 .circleci/deploy.sh
        ssh-keyscan $CODEDAMNIP >> ~./ssh/known_hosts 
          if [ ! -f "package.json" ]; then
            echo
            echo "---"
            echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
            echo "---"
            echo
            echo "Current directory: $(pwd)"
            echo
            echo
            echo "List directory: "
            echo
            ls
            exit 1
          fi
        name: Checking for package.json.
        working_directory: ~/project
    - restore_cache:
        keys:
        - node-deps-v1-{{ .Branch }}-{{ checksum "~/project/package-lock.json" }}
    - run:
        command: "if [[ ! -z \"\" ]]; then\n  echo \"Running override package installation command:\"\n  \nelse\n  npm ci\nfi\n"
        name: Installing NPM packages
        working_directory: ~/project
    - save_cache:
        key: node-deps-v1-{{ .Branch }}-{{ checksum "~/project/package-lock.json" }}
        paths:
        - ~/.npm
    - run:
        command: npm run test
        name: Run NPM Tests
        working_directory: ~/project
    - run:
        name: DEV
        command: export NODE_ENV=development 
    - run:
        name: Install Dependencies
        command: "if [[ ! -z \"\" ]]; then\n  echo \"Running override package installation command:\"\n  \nelse\n  npm ci\nfi\n"
        name: Installing NPM packages
        working_directory: ~/project
    - run:
        name: Deploy
        command: ./.circleci/deploy.sh

workflows:
  node-tests:
    jobs:
    - test_and_deploy
  version: 2

# Original config.yml file:
# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test